### PR TITLE
Add custom script ability

### PR DESCRIPTION
**Pull request by alexcouper**
Adds a configureable script section in the builder.ini which makes compbuild extensible by end users.

### CODE REVIEW

**Comment by alexcouper** [comment]
#selfmerge @txels feel free to comment....

**Comment by txels** [comment]
Wouldn't it have been simpler to just pass through to arbitrary makefile targets? E.g. `compbuild <blah>` to be `make <blah>` for the component...

**Comment by alexcouper** [comment]
It would have been. The point of this is to be able to run things that are outside of the knowledge of each component (where as a make target requires adding something to each of them).

It means that things (like the adhoc verification of docker images) can be run locally via changes to the builder.ini 

In time, organizational level concerns/standards can be enforced globally through these kind of additions, rather than components needing to subscribe to them themselves

**Comment by txels** [comment]
Ah yes I see now. This is in a single predefined section in the builder.ini file, not per component.

**Pull request merged**
