### PR TITLE
Fix component label manipulations, remove label was broken

### PR DESCRIPTION
**Pull request by holmars**
Fixes a bug when trying to remove a label from a PR 😭

### CODE REVIEW

**Comment by alexcouper** [comment]
👍

**Comment by holmars** [comment]
Something strange going on:
screen shot 2017-01-20 at 11 03 55

**Comment by alexcouper** [comment]
lol - oh yes, Azazo's jenkinsfile uses a different flow where this won't be possible.

The jenkinsfile contains something like:
```
for thing in $(compbuild discover):
    compbuild build $thing
    compbuild test $thing
```

Meaning that `components` passed in [here](https://github.com/ployst/component-builder/pull/26/files#diff-85a9d33adac257b45ad892b2d94d8a07L83) is always just one thing so all other components are removed :(

**Comment by alexcouper** [comment]
Perhaps you could separate out `declare_component_usage` from the run command (it doesn't need to be done every time anyway). `compbuild declare` could then be run at the top of the jenkins file and just perform that part.

**Comment by holmars** [comment]
Ok, will do :)

**Pull request merged**
